get_filename_component(NCINE_LIBRARY_DIRECTORY ${NCINE_LOCATION} DIRECTORY)
get_filename_component(NCINE_LIBRARY_NAME ${NCINE_LOCATION} NAME)
get_filename_component(NCINE_LIBRARY_EXT ${NCINE_LOCATION} EXT)
string(REPLACE "${NCINE_LIBRARY_EXT}" "" NCINE_LIBRARY_NAME_WLE ${NCINE_LIBRARY_NAME}) # NAME_WLE on CMake < 3.14

set(NCPONG_LUA_IN ${CMAKE_SOURCE_DIR}/ncpong.lua)
set(NCPONG_LUA ${CMAKE_BINARY_DIR}/ncpong.lua)
configure_file(${NCPONG_LUA_IN} ${NCPONG_LUA} @ONLY)

install(FILES ${NCPONG_LUA} DESTINATION ${RUNTIME_INSTALL_DESTINATION})
