set(NCPONG_OPTIONS_PRESETS "Default" CACHE STRING "Presets for CMake options")
set_property(CACHE NCPONG_OPTIONS_PRESETS PROPERTY STRINGS Default BinDist)

if(NCPONG_OPTIONS_PRESETS STREQUAL BinDist)
	message(STATUS "Options presets: ${NCPONG_OPTIONS_PRESETS}")

	set(CMAKE_BUILD_TYPE Release)
	set(CMAKE_CONFIGURATION_TYPES Release)
	set(DEFAULT_DATA_DIR_DIST ON)
	set(NCPONG_PREPARE_ANDROID OFF)
endif()
